const filmListesi = [
    "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Godfather Part II", "12 Angry Men", 
    "Schindler's List", "The Lord of the Rings: The Return of the King", "Pulp Fiction", 
    "The Lord of the Rings: The Fellowship of the Ring", "The Good, the Bad and the Ugly", "Forrest Gump", 
    "Fight Club", "The Lord of the Rings: The Two Towers", "Inception", "Star Wars: Episode V - The Empire Strikes Back", 
    "The Matrix", "Goodfellas", "One Flew Over the Cuckoo's Nest", "Se7en", "It's a Wonderful Life", 
    "Seven Samurai", "The Silence of the Lambs", "Saving Private Ryan", "City of God", "Interstellar", 
    "Life Is Beautiful", "The Green Mile", "Star Wars: Episode IV - A New Hope", "Terminator 2: Judgment Day", 
    "Back to the Future", "Spirited Away", "Psycho", "The Pianist", "Parasite", "Leon: The Professional", 
    "The Lion King", "Gladiator", "American History X", "The Departed", "The Usual Suspects", "The Prestige", 
    "Casablanca", "Whiplash", "The Intouchables", "Grave of the Fireflies", "Harakiri", "Modern Times", 
    "Once Upon a Time in the West", "Rear Window", "Alien", "City Lights", "Cinema Paradiso", "Apocalypse Now", 
    "Memento", "Raiders of the Lost Ark", "Django Unchained", "WALL-E", "The Lives of Others", "Sunset Blvd.", 
    "Paths of Glory", "The Shining", "The Great Dictator", "Avengers: Infinity War", "Witness for the Prosecution", 
    "Aliens", "Spider-Man: Into the Spider-Verse", "American Beauty", "Dr. Strangelove", "The Dark Knight Rises", 
    "Oldboy", "Inglourious Basterds", "Amadeus", "Coco", "Toy Story", "Braveheart", "Joker", "Das Boot", 
    "Avengers: Endgame", "Princess Mononoke", "Once Upon a Time in America", "Good Will Hunting", "Your Name.", 
    "Requiem for a Dream", "3 Idiots", "Singin' in the Rain", "Toy Story 3", "High and Low", 
    "Star Wars: Episode VI - Return of the Jedi", "Eternal Sunshine of the Spotless Mind", "2001: A Space Odyssey", 
    "Reservoir Dogs", "Capernaum", "Citizen Kane", "Lawrence of Arabia", "The Hunt", "M", "North by Northwest", 
    "Vertigo", "Amélie", "Snatch", "A Clockwork Orange", "Full Metal Jacket", "Scarface", "Double Indemnity", 
    "The Apartment", "Taxi Driver", "To Kill a Mockingbird", "The Sting", "Up", "L.A. Confidential", "Heat", 
    "Metropolis", "Hamilton", "Die Hard", "Indiana Jones and the Last Crusade", "Incendies", "Kid A", 
    "A Separation", "Bicycle Thieves", "Raging Bull", "Batman Begins", "Dangal", "Downfall", "Like Stars on Earth", 
    "The Wolf of Wall Street", "Green Book", "Judgment at Nuremberg", "Ran", "Casino", "Pan's Labyrinth", 
    "My Neighbor Totoro", "The Secret in Their Eyes", "There Will Be Blood", "Unforgiven", "Shutter Island", 
    "The Sixth Sense", "Monty Python and the Holy Grail", "Jurassic Park", "A Beautiful Mind", 
    "No Country for Old Men", "The Truman Show", "Kill Bill: Vol. 1", "Finding Nemo", "Memories of Murder", 
    "Trainspotting", "The Bridge on the River Kwai", "Fargo", "Gran Torino", "My Father and My Son", 
    "Gone with the Wind", "Wild Strawberries", "The Third Man", "Stalker", "Deer Hunter", "The Big Lebowski", 
    "The Elephant Man", "Blade Runner", "Sherlock Jr.", "On the Waterfront", "Mary and Max", "Dial M for Murder", 
    "Gone Girl", "Howl's Moving Castle", "The Grand Budapest Hotel", "V for Vendetta", "Before Sunrise", 
    "Ben-Hur", "Prisoners", "12 Years a Slave", "Warrior", "Harry Potter and the Deathly Hallows: Part 2", 
    "Mad Max: Fury Road", "The General", "The Gold Rush", "Million Dollar Baby", "Catch Me If You Can", 
    "Stand by Me", "Hachi: A Dog's Tale", "The Help", "To Be or Not to Be", "Logan", "Platoon", "Into the Wild", 
    "The 400 Blows", "Dead Poets Society", "The Handmaiden", "Rush", "Life of Brian", "Persona", "Hacksaw Ridge", 
    "Hotel Rwanda", "Andrei Rublev", "The Seventh Seal", "Rocky", "Room", "Ford v Ferrari", "Wild Tales", 
    "Butch Cassidy and the Sundance Kid", "Spotlight", "Barry Lyndon", "The Terminator", "Portrait of a Lady on Fire", 
    "The Wizard of Oz", "In the Name of the Father", "Monsters, Inc.", "The Grapes of Wrath", "1917", "Jaws", 
    "The Exorcist", "Pirates of the Caribbean: The Curse of the Black Pearl", "Groundhog Day", "Ratatouille", 
    "The Best Years of Our Lives", "The Thing", "Blade Runner 2049", "The Incredibles", "Rebecca", "Cool Hand Luke", 
    "It Happened One Night", "Casino Royale", "Sin City", "The Graduate", "Amores Perros", "Slumdog Millionaire", 
    "How to Train Your Dragon", "The Iron Giant", "Lock, Stock and Two Smoking Barrels", "The Night of the Hunter", 
    "The Passion of Joan of Arc", "Toy Story 2", "Network", "The Maltese Falcon", "The Great Escape", "Gandhi", 
    "Star Wars: Episode VII", "Black Swan", "The Revenant", "Twelve Monkeys", "The Princess Bride", "Tangled", 
    "Inside Out", "Zootopia", "Moana", "Klaus", "Soul", "Luca", "Encanto", "Puss in Boots: The Last Wish", 
    "Spider-Man: Across the Spider-Verse", "The Boy and the Heron", "Everything Everywhere All at Once", 
    "Top Gun: Maverick", "Oppenheimer", "Barbie", "Killers of the Flower Moon", "Poor Things", "Anatomy of a Fall", 
    "The Zone of Interest", "Past Lives", "Dune: Part Two", "Furiosa: A Mad Max Saga", "Deadpool & Wolverine", 
    "Gladiator II", "Joker: Folie à Deux", "Alien: Romulus", "Twisters", "Kingdom of the Planet of the Apes", 
    "Civil War", "Challengers", "Hit Man", "Monkey Man", "Late Night with the Devil", "The Holdovers", 
    "American Fiction", "The Iron Claw", "Priscilla", "Ferrari", "Maestro", "Napoleon", "The Killer", 
    "Society of the Snow", "Godzilla Minus One", "Talk to Me", "Evil Dead Rise", "John Wick: Chapter 4", 
    "Creed III", "Scream VI", "Barbarian", "Pearl", "X", "The Menu", "Bullet Train", "Elvis", "Tár", 
    "The Banshees of Inisherin", "The Fabelmans", "Triangle of Sadness", "Aftersun", "All Quiet on the Western Front", 
    "Avatar: The Way of Water", "Guillermo del Toro's Pinocchio", "Marcel the Shell with Shoes On", "Turning Red", 
    "The Sea Beast", "Puss in Boots", "Kung Fu Panda", "How to Train Your Dragon 2", "Big Hero 6", "Isle of Dogs", 
    "A Silent Voice", "Wolf Children", "The Red Turtle", "My Life as a Zucchini", "Kubo and the Two Strings", 
    "Anomalisa", "Shaun the Sheep Movie", "Song of the Sea", "The Tale of the Princess Kaguya", "The Wind Rises", 
    "Ernest & Celestine", "Wreck-It Ralph", "ParaNorman", "Frankenweenie", "Rango", "Chico & Rita", 
    "The Illusionist", "Coraline", "Persepolis", "Paprika", "Cars", "Monster House", "Corpse Bride", 
    "Wallace & Gromit: The Curse of the Were-Rabbit", "The Polar Express", "Shark Tale", "Shrek", "Chicken Run", 
    "Mulan", "Nightmare Before Christmas", "Aladdin", "Beauty and the Beast", "Castle in the Sky", "Akira", 
    "Nausicaä of the Valley of the Wind"
    // Liste 500'e tamamlanacak şekilde tekrar edenleri temizleyip veri çekmeye hazırdır.
];