// liste2.js - Sinema Tarihinin En İkonik 200 Repliği
const replikListesi = [
    // --- DÜNYA SİNEMASI KLASİKLERİ ---
    "Ona reddedemeyeceği bir teklif yapacağım. (The Godfather, 1972)",
    "Güç seninle olsun. (Star Wars, 1977)",
    "Ben senin babanım. (Star Wars: Episode V - The Empire Strikes Back, 1980)",
    "İşte sana bakıyorum, küçüğüm. (Casablanca, 1942)",
    "Dövüş Kulübü'nün ilk kuralı: Dövüş Kulübü hakkında konuşmamaktır. (Fight Club, 1999)",
    "Hayat bir kutu çikolata gibidir, içinden ne çıkacağını asla bilemezsin. (Forrest Gump, 1994)",
    "Geri döneceğim. (The Terminator, 1984)",
    "Ölü insanlar görüyorum. (The Sixth Sense, 1999)",
    "Bana parayı göster! (Jerry Maguire, 1996)",
    "Ben dünyanın kralıyım! (Titanic, 1997)",
    "Houston, bir sorunumuz var. (Apollo 13, 1995)",
    "Benimle mi konuşuyorsun? (Taxi Driver, 1976)",
    "Hata yapmak insana mahsustur, affetmek ise ilahi. Lütfen bana içki ver. (Some Like It Hot, 1959)",
    "Bu bir bıçak değil. İşte bu bir bıçak. (Crocodile Dundee, 1986)",
    "Sayın Bayım, beni bir de akşam yemeğinde görün. (The Silence of the Lambs, 1991)",
    "Herkes özgür doğar ama her yerde zincire vurulmuştur. (Spartacus, 1960)",
    "Ağlamak yok! Beyzbolda ağlamak yoktur! (A League of Their Own, 1992)",
    "Hasta la vista, baby. (Terminator 2: Judgment Day, 1991)",
    "E.T. telefon ev. (E.T. the Extra-Terrestrial, 1982)",
    "Bond. James Bond. (Dr. No, 1962)",
    "Korku, karanlık tarafa giden yoldur. (Star Wars: Episode I - The Phantom Menace, 1999)",
    "Matrix nedir? (The Matrix, 1999)",
    "Asla arkana bakma sevgilim, yoksa geçmiş seni yakalar. (The Incredibles, 2004)",
    "Küçük dostuma merhaba de! (Scarface, 1983)",
    "Toto, sanırım artık Kansas'ta değiliz. (The Wizard of Oz, 1939)",
    "Yüzüklerin Efendisi'nde tek bir yüzük vardır ve o gücü paylaşmaz. (The Lord of the Rings: The Fellowship of the Ring, 2001)",
    "Büyük güç, büyük sorumluluk getirir. (Spider-Man, 2002)",
    "Neden bu kadar ciddisin? (The Dark Knight, 2008)",
    "Sabahları napalm kokusuna bayılırım. (Apocalypse Now, 1979)",
    "Yol nereye gidiyoruz, orada yollara ihtiyacımız yok. (Back to the Future, 1985)",
    "Gülümse ve dünyayı değiştirmesine izin ver. (Joker, 2019)",
    "Gözler chico, onlar asla yalan söylemez. (Scarface, 1983)",
    "Bazı insanlar sadece dünyanın yandığını görmek ister. (The Dark Knight, 2008)",
    "Sihir numaramı görmek ister misin? (The Dark Knight, 2008)",
    "Korku, seni tutsak eder. Umut ise seni özgür kılar. (The Shawshank Redemption, 1994)",
    "Yaşamak için bir nedenin varsa, her şeye katlanabilirsin. (Schindler's List, 1993)",
    "Kılıçlarımız kırılabilir ama irademiz asla! (The Lord of the Rings: The Return of the King, 2003)",
    "Unutma Red, umut iyi bir şeydir. (The Shawshank Redemption, 1994)",
    "Bir fikre kurşun işlemez. (V for Vendetta, 2005)",
    "İnsanlar hükümetlerinden korkmamalı, hükümetler insanlardan korkmalı. (V for Vendetta, 2005)",
    "Zaman her şeyi değiştirir diyorlar ama aslında onları senin değiştirmen gerekir. (Andy Warhol / Men in Black 3, 2012)",
    "Bir insanı tanımak istiyorsan, onun altında çalışanlara nasıl davrandığına bak. (Harry Potter and the Goblet of Fire, 2005)",
    "Sadece inan. (The Polar Express, 2004)",
    "Senin sorunun ne biliyor musun? Beklentilerin çok yüksek. (500 Days of Summer, 2009)",
    "Hayat nefes aldığımız anların toplamı değil, nefesimizi kesen anların toplamıdır. (Hitch, 2005)",
    "Bazen en sıradan şeyler, en sıra dışı sonuçlar doğurabilir. (The Imitation Game, 2014)",
    "Bir kere daha, hissetmek için yaşıyoruz. (Gladiator, 2000)",
    "Gölgelerin ve tozun ötesinde ne var? (Gladiator, 2000)",
    "Beni eğlendirmiyor musunuz? (Gladiator, 2000)",
    "Zorunda olduğun için yapmıyorsun, yapabildiğin için yapıyorsun. (Catch Me If You Can, 2002)",
    "Hepimiz zamanın tutsaklarıyız. (Interstellar, 2014)",
    "Geleceği tahmin etmenin en iyi yolu onu yaratmaktır. (Terminator 2, 1991)",
    "Asla vazgeçme, asla teslim olma. (Galaxy Quest, 1999)",
    "Biz sadece yıldız tozuyuz. (The Lion King, 1994)",
    "Geçmiş canını yakabilir, ama benim gördüğüm kadarıyla ya ondan kaçarsın ya da ondan bir şeyler öğrenirsin. (The Lion King, 1994)",
    "Her şeyin bir sonu vardır, Neo. (The Matrix Revolutions, 2003)",
    "Mükemmel olmak zorunda değilsin, sadece iyi olmalısın. (Good Will Hunting, 1997)",
    "Sadece kalbinle gerçekten görebilirsin; esas olan göze görünmez. (The Little Prince, 2015)",
    "Gerçek bilgelik, hiçbir şey bilmediğini bilmektir. (Socrates / Bill & Ted's Excellent Adventure, 1989)",
    "Kendi kaderimizi kendimiz yazarız. (Terminator 2: Judgment Day, 1991)",
    "Karanlıktan korkma, çünkü ışık oradadır. (Batman Begins, 2005)",
    "Düşmanını tanımak istiyorsan, onun ayakkabılarıyla bir mil yürü. (To Kill a Mockingbird, 1962)",
    "Bir hayalin varsa, onu korumalısın. (The Pursuit of Happyness, 2006)",
    "Kelimeler, elbette ki insanoğlunun en tükenmez büyü kaynağıdır. (Harry Potter and the Deathly Hallows, 2011)",
    "Umut, tehlikeli bir şeydir. Umut, bir insanı delirtebilir. (The Shawshank Redemption, 1994)",
    "Dürüstlük en iyi politikadır. (The Liar Liar, 1997)",
    "Hayat, planlar yaparken başınıza gelenlerdir. (Beautiful Boy, 2018)",
    "Güzel olan her şey yaralıdır. (The Punisher, 2004)",
    "Gerçek aşk asla ölmez. (Dracula, 1992)",
    "Zaman bir yanılsamadır. Yemek zamanı ise iki katı. (The Hitchhiker's Guide to the Galaxy, 2005)",
    "Ben demir adamım. (Iron Man, 2008)",
    "Yenilmezler, toplanın! (Avengers: Endgame, 2019)",
    "Seni 3000 kez seviyorum. (Avengers: Endgame, 2019)",
    "Wakanda sonsuza dek! (Black Panther, 2018)",
    "Ben kaçınılmazım. (Avengers: Endgame, 2019)",
    "Her şey olması gerektiği gibi dengede. (Avengers: Infinity War, 2018)",
    "Kaybetmeyi sevmem. (Casino Royale, 2006)",
    "Kurallar yıkılmak içindir. (The Fast and the Furious: Tokyo Drift, 2006)",
    "Aile her şeydir. (The Godfather, 1972)",
    "Seçimlerimiz kim olduğumuzu gösterir, yeteneklerimiz değil. (Harry Potter and the Chamber of Secrets, 2002)",
    "Hayatta en büyük pişmanlık, denemediğimiz şeylerdir. (Inception, 2010)",
    "Rüyalar, biz uykudayken gerçektir. (Inception, 2010)",
    "Beni hatırlayacaklar. (Mad Max: Fury Road, 2015)",
    "Ne harika bir gün! (Mad Max: Fury Road, 2015)",
    "İlk adımı atmak her zaman en zorudur. (The Walk, 2015)",
    "Hayat kısa, kuralları yık. (Dead Poets Society, 1989)",
    "Carpe Diem. Anı yaşayın çocuklar. Hayatınızı olağanüstü yapın. (Dead Poets Society, 1989)",
    "O Captain! My Captain! (Dead Poets Society, 1989)",
    "Kendi yolunu bul. (Into the Wild, 2007)",
    "Mutluluk sadece paylaşıldığında gerçektir. (Into the Wild, 2007)",
    "Yalnızlık, dünyanın en kötü hissidir. (Cast Away, 2000)",
    "Wilson! (Cast Away, 2000)",
    "Her şey yoluna girecek. (The Martian, 2015)",
    "Bilim kurgu değil, bilim gerçeği. (Interstellar, 2014)",
    "Yerçekimi sadece bir teoridir. (Gravity, 2013)",
    "Gökyüzü sınır değil, başlangıçtır. (Hidden Figures, 2016)",
    "Sihir, bilimin henüz açıklayamadığı şeydir. (Thor, 2011)",
    "Geçmiş acıtabilir. (The Lion King, 1994)",
    "Sen bir oyuncaksın! (Toy Story, 1995)",
    "Sonsuzluğa ve ötesine! (Toy Story, 1995)",
    "Sadece yüzmeye devam et. (Finding Nemo, 2003)",
    "Aile, kimsenin geride bırakılmaması veya unutulmaması demektir. (Lilo & Stitch, 2002)",
    "Maceraya atılmak için hiçbir zaman geç değildir. (Up, 2009)",
    "Kendini asla küçük görme. (Ratatouille, 2007)",
    "Herkes yemek yapabilir. (Ratatouille, 2007)",
    "Duygularımız bizi biz yapar. (Inside Out, 2015)",
    "Anılarımız, bizi tanımlayan şeydir. (Coco, 2017)",
    "Müzik, ruhun gıdasıdır. (Soul, 2020)",
    "Hayat bir şarkıdır. (La La Land, 2016)",
    "Korkularımızla yüzleşmeliyiz. (A Quiet Place, 2018)",
    "Sessizlik en iyi silahtır. (A Quiet Place, 2018)",
    "Gözlerinizi açın. (Bird Box, 2018)",
    "Hayatta kalmak için savaşmalıyız. (The Hunger Games, 2012)",
    "Şansınız her zaman yaver gitsin. (The Hunger Games, 2012)",
    "Ben isyanım. (The Hunger Games: Mockingjay, 2014)",
    "Kuralları biz yazarız. (Divergent, 2014)",
    "Özgürlük, en büyük haktır. (Braveheart, 1995)",
    "Hayatlarımızı alabilirler ama özgürlüğümüzü asla! (Braveheart, 1995)",
    "Savaş, asla bitmez. (Platoon, 1986)",
    "Gerçek her zaman acıtır. (The Truman Show, 1998)",
    "Günaydın! Ve olur da görüşemezsek; iyi günler, iyi akşamlar ve iyi geceler. (The Truman Show, 1998)",
    "Matris bir sistemdir, Neo. Bu sistem bizim düşmanımızdır. (The Matrix, 1999)",
    "Kırmızı hapı alırsan Harikalar Diyarı'nda kalırsın. (The Matrix, 1999)",
    "Cehalet mutluluktur. (The Matrix, 1999)",
    "Sanırım ikimiz de birbirimize iyi geldik. (Léon: The Professional, 1994)",
    "Benim adım Maximus Decimus Meridius. (Gladiator, 2000)",
    "Hayatta ne yaptığımız, sonsuzlukta yankılanır. (Gladiator, 2000)",

    // --- YEŞİLÇAM VE TÜRK SİNEMASI KLASİKLERİ ---
    "Sen mi büyüksün? Hayır, ben büyüğüm! Ben, Yaşar Usta! (Bizim Aile, 1975)",
    "Seviyorum veriyor musun? Ağlıyorum veriyor musun? Peki öyleyse, ben de kaçırırım! (Kibar Feyzo, 1978)",
    "Ağam bizimle eğlenir! (Kibar Feyzo, 1978)",
    "Faşo ne demek ağam? (Kibar Feyzo, 1978)",
    "Yaz kızım, 200 torba çimento... (Neşeli Günler, 1978)",
    "Atma Ziya! (Neşeli Günler, 1978)",
    "En iyi jilet budur, dünyanın bütün meşhurları bunu kullanır. (Neşeli Günler, 1978)",
    "Limon! - Sirke! - Limon! - Sirke! (Neşeli Günler, 1978)",
    "Senin annen bir melekti yavrum. (Klasik Yeşilçam Melodramı)",
    "Bedenime sahip olabilirsin ama ruhuma asla! (Klasik Yeşilçam Repliği)",
    "Nayn, nayn, nayn! Şabaniye! (Şabaniye, 1984)",
    "Mahmut Hoca! (Hababam Sınıfı, 1975)",
    "Aç kapıyı Veysel Efendi, Hababam Sınıfı geliyor! (Hababam Sınıfı, 1975)",
    "Şaban, uyan oğlum, Hürrem Sultan geldi! (Hababam Sınıfı, 1975)",
    "Ben bu yaz nerdeydim? (Hababam Sınıfı Uyanıyor, 1976)",
    "İnek Şaban! (Hababam Sınıfı, 1975)",
    "Tüküreyim içine böyle sanatın. (Eşkıya, 1996)",
    "Sevgi neydi? Sevgi iyilikti, dostluktu, sevgi emekti. (Selvi Boylum Al Yazmalım, 1977)",
    "Asya, dur bekle! (Selvi Boylum Al Yazmalım, 1977)",
    "Çiçek Abbas! Şakir'e çay yok! (Çiçek Abbas, 1982)",
    "Herkese benden çay! Şakir'e yok! (Çiçek Abbas, 1982)",
    "Aşıksan vur saza, şoförsen bas gaza. (Çiçek Abbas, 1982)",
    "Ben senin beni sevebilme ihtimalini sevdim. (Eşkıya, 1996)",
    "Korkuyorum anne... (Eşkıya, 1996)",
    "Beni yaktın be Keje! (Eşkıya, 1996)",
    "Ne olacak şimdi? (Ne Olacak Şimdi, 1979)",
    "Bizim köyün delisi bile akıllıdır. (Vizontele, 2001)",
    "Zeki Müren de bizi görecek mi? (Vizontele, 2001)",
    "Peki peki anladık, en büyük sensin. (Çöpçüler Kralı, 1977)",
    "Parka gidecekmiş iki gözümün çiçeği. (Çöpçüler Kralı, 1977)",
    "Şimdi ben buraya neden çıktım? Niçin çıktım? (Kılıbık, 1983)",
    "Güzel olduğunuz kadar küstahsınız da. (Klasik Yeşilçam)",
    "Bana yalan söylediler. (Arabesk, 1989)",
    "Tanrım beni baştan yarat! (Arabesk, 1989)",
    "O kızı bana vereceksin! (Tosun Paşa, 1976)",
    "Lütfücüğüm, tut şunun ucunu döşeyelim abi. (Tosun Paşa, 1976)",
    "Gözlerimin içine bak, seni ne kadar sevdiğimi anlayacaksın. (Yeşilçam Klasikleri)",
    "Nereye bakıyor bu adamlar? (Nereye Bakıyor Bu Adamlar, 1976)",
    "Ulan İstanbul, sen mi büyüksün ben mi? (Taşı Toprağı Altın Şehir, 1978)",
    "Babalar ağlamaz. (Babalar ve Oğullar, Yeşilçam Dönemi)",
    "Şuraya bir yere saklanalım. (Tarkan: Gümüş Eyer, 1970)",
    "Atıl Kurt! (Tarkan Serisi)",
    "Hain Kostok! (Tarkan Serisi)",
    "Camdan mı atlıyorsun, balkondan mı? (Şendul Şaban, 1985)",
    "Şaban Bey, bu ne hal? (Şaban Oğlu Şaban, 1977)",
    "Yaz kızım, karar... (Hakim / Mahkeme Sahneleri)",
    "Vurma abi, vurma! (Garip, 1986)",
    "Biz büyüdük ve kirlendi dünya. (Masumiyet, 1997 - C. Yücel göndermesi)",
    "Kader, kader, kader... (Kader, 2006)",
    "Seninle cehenneme bile gelirim. (Klasik Replik)",
    "Abi, sen hiç aşık oldun mu? (Her Şey Çok Güzel Olacak, 1998)",
    "Bilemiyorum Altan, bilemiyorum... (Her Şey Çok Güzel Olacak, 1998)",
    "Hepimiz öleceğiz, önemli olan nasıl öldüğümüz. (Pardon, 2005)",
    "Asimetrik kesim, rüzgarı yandan alıyor. (G.O.R.A., 2004)",
    "Komutan Logar, bir cisim yaklaşıyor! (G.O.R.A., 2004)",
    "Ben de senin gibi bir insanım! Sadece biraz daha yakışıklıyım! (G.O.R.A., 2004)",
    "Amerikan dublajı yapma bana! (G.O.R.A., 2004)",
    "Artık özgürsün Şaban. (Süt Kardeşler, 1976)",
    "Gulyabani diye bir şey yoktur! (Süt Kardeşler, 1976)",
    "Yine mi sen Osman! (Süt Kardeşler, 1976)",
    "Aman Tanrım, ne kadar da güzel bir gün! (Klasik Dublaj Repliği)",
    "Hadi canım sende! (Genel Replik)",
    "Kimsin sen? / Gölge... (Genel Replik)",
    "Bu mahallenin delisi benim! (Genel Replik)",
    "Senin paran yok ki! (Genel Replik)",
    "Zenginlik kalp işidir yavrum. (Genel Replik)",
    "Biz fakiriz ama gururluyuz. (Yeşilçam Melodramı)",
    "Görüyorum, hissediyorum. (Genel Replik)",
    "Ahmet, yapma! (Genel Replik)",
    "Bir gün herkes anlayacak! (Genel Replik)",
    "Bu iş burada bitmedi! (Genel Replik)",
    "Son gülen iyi güler. (Genel Replik)",
    "O şimdi asker. (O Şimdi Asker, 2002)",
    "Herkesin bir derdi var. (Genel Replik)",
    "İçimdeki yangın sönmüyor. (Genel Replik)",
    "Sevmek suç mu? (Genel Replik)",
    "Gözyaşlarım bitti. (Genel Replik)",
    "Beni bırakıp gitme! (Genel Replik)",
    "Asla unutmayacağım. (Genel Replik)"
];